version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7.18
    container_name: mysql-lable
    volumes:
      - /apps/mydir:/mydir
      - /apps/datadir:/var/lib/mysql
      - /apps/conf/my.cnf:/etc/my.cnf      
      - /apps/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD= ac1234"
      - "MYSQL_DATABASE= mydb"      
    ports:
      
      - 3306:3306
